# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
  use_frameworks!

target 'ObjectiveCExample' do

 pod 'iZootoiOSSDK', :path=> "../iZootoiOSSDK/"


target 'NotificationExtesnionServices' do
 pod 'iZootoiOSSDK', :path=> "../iZootoiOSSDK/"
end

end
