# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iZootoiOSProject' do
  use_frameworks!
  pod 'iZootoiOSSDK', :path=> "../iZootoiOSSDK/"

target 'iZootoNotificationExtendsServices' do
  pod 'iZootoiOSSDK', :path=> "../iZootoiOSSDK/"
end
end